displayName=UIM Utilities
author=Jake
description=Quality of life and safety warnings for ultimate ironman accounts
tags=jake,uim,ultimate ironman,ironman,utilities,warning,items,item,ground,drop,dropped,deathpile,floor,storage,cox,chambers,xeric,olm,raid,raids,exit,leave,looting bag,loot,bag,destroy,protect,shop,sell,store,general store
plugins=com.uimutilities.UimUtilitiesPlugin
build=standard
